name: Deploy or Destroy AWS Infra (VPC + RDS + Lambda + API Gateway)

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_ACTION: apply  # apply | destroy
      AWS_REGION: us-east-1

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar com AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::757367947438:role/GitHubOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Apply
        if: env.TF_ACTION == 'apply'
        working-directory: infra
        run: |
          echo "🚀 Aplicando toda a infraestrutura..."
          terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Terraform Destroy
        if: env.TF_ACTION == 'destroy'
        working-directory: infra
        run: |
          echo "🧨 Destruindo toda a infraestrutura..."
          terraform destroy -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"
