name: Update Lambda Code

on:
  push:
    branches:
      - update

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    env:
      LAMBDA_RESOURCE_NAME: items

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar com AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::757367947438:role/GitHubOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan (refresh)
        working-directory: infra
        run: |
          echo "🔄 Sincronizando estado com AWS..."
          terraform plan

      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar Lambda com Maven
        working-directory: lambda
        run: mvn clean package -U

      - name: Copiar JAR gerado para pasta de deploy
        run: |
          mkdir -p infra/build/lambda
          cp lambda/target/hello-lambda-1.0.jar infra/build/lambda/lambda.jar

      - name: Atualizar código da Lambda
        working-directory: infra
        run: |
          echo "Atualizando apenas o código da Lambda..."
          terraform apply \
            -target=aws_lambda_function.${LAMBDA_RESOURCE_NAME} \
            -auto-approve
